services:
  database:
    container_name: quiz-database
    image: postgres:latest
    restart: always
    shm_size: 256mb
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: pg_isready -d ${DB_NAME} -U ${DB_USERNAME} -h database
      interval: 2s
      timeout: 3s
      retries: 120
    ports:
      - ${DB_PORT}:5432
